# Generated by Django 4.1.13 on 2025-03-01 23:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=255)),
                ('annualIncome', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthlyExpenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('savingsAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investmentExperience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('riskTolerance', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('financialGoals', models.TextField(blank=True)),
                ('hasEmergencyFund', models.BooleanField(default=False)),
                ('hasDebts', models.BooleanField(default=False)),
                ('_interestedTopics', models.TextField(blank=True, db_column='interestedTopics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
